# Generated by Django 4.1.5 on 2023-01-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='statuses.status', verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
