# Generated by Django 4.1.2 on 2022-11-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_author_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(to='core.label'),
        ),
    ]
